sudo: required
service:
 - docker
before_install:
  - docker build -t shnkar007/travis:v1.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push shnkar007/travis:v1.0
notifications:
 email:
   recipients:
     - sankarraman.vedagiri@gmail.com
   on_success: always
   on_failure: always
